[app]
name = "goo"
env = "local"
debug = true

[db]
connection = "mysql"
host = "127.0.0.1"
port = "3306"
database = "goo"
username = "admin"
password = "123456"

[cache]
drive = "redis"

[redis]
host = "127.0.0.1"
port = "6379"
auth = ""
database = 0

[queue]
drive = "rabbitmq"

[rabbitmq]
host = "127.0.0.1"
port = "5672"
user = "admin"
pass = "admin"
vhost = "/"

[msa]
rpc_addr = "127.0.0.1:9930"

[error]
report = "http://10.0.0.3:8901/"
